version: '3.9'

services:
  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    volumes:
      - mysql:/var/lib/mysql
      - ./db_init/GONGBU.sql:/docker-entrypoint-initdb.d/GONGBU.sql
    expose:
      - 3306
    ports:
      - "33060:3306"
    restart: unless-stopped
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
      - ./finetune_output:/finetune_output
      # - ./bert-base-chinese:/backend/bert-base-chinese
      - ./roberta-large:/backend/roberta-large
      - ./ext:/backend/ext
      - ./logs:/backend/logs
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:pwd@db:3306/db
      - MODEL_PATH=/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /backend
  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - /frontend/node_modules
    depends_on:
      - api
    environment:
      - VITE_BACKEND=http://localhost:8000
      - VITE_DEFAULT_MODEL_OUTPUT=/finetune_output
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
        - action: rebuild
          path: ./frontend/package.json
volumes:
  mysql: