version: '3'

tasks:
  dev:
    cmds:
    - docker compose -f ./docker-compose.yaml up -d
    - docker compose -f ./docker-compose.yaml watch

  dev-mr:
    cmds:
    - docker compose -f ./docker-compose.mirror.yaml up -d
    - docker compose -f ./docker-compose.mirror.yaml watch


  format:
    cmds:
    - python -m pip install black
    - black .
    - cd frontend && npx prettier --write .
