FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-devel

RUN apt-get update
RUN apt-get install -y apt-utils
# Install wget
RUN apt-get install -y git git-lfs wget curl postgresql-client net-tools iputils-ping vim tmux

# micromamba
COPY ./dep/linux_mb.tar.bz2 /conf/linux_mb.tar.bz2
RUN mkdir /micromamba
RUN tar -xjf /conf/linux_mb.tar.bz2 -C /micromamba
RUN /micromamba/bin/micromamba shell init -s bash -p ~/micromamba
RUN echo "alias mb=micromamba" >> ~/.bashrc
RUN echo "alias conda=micromamba" >> ~/.bashrc
RUN rm /conf/linux_mb.tar.bz2

# Create the env for the backend
COPY ./requirements.txt /conf/requirements.txt

RUN /micromamba/bin/micromamba create -y -n backend -c conda-forge python=3.10
# Install packaging
RUN /micromamba/bin/micromamba run -n backend pip install packaging

# Cache some very large packages
RUN /micromamba/bin/micromamba run -n backend pip install nvidia-cublas-cu12
RUN /micromamba/bin/micromamba run -n backend pip install nvidia-cuda-cupti-cu12
RUN /micromamba/bin/micromamba run -n backend pip install nvidia-cuda-nvrtc-cu12
RUN /micromamba/bin/micromamba run -n backend pip install nvidia-cuda-runtime-cu12
RUN /micromamba/bin/micromamba run -n backend pip install scipy==1.11.4
RUN /micromamba/bin/micromamba run -n backend pip install mkl-service==2.4.0
RUN /micromamba/bin/micromamba run -n backend pip install --no-deps bert-score

RUN /micromamba/bin/micromamba run -n backend pip install -r /conf/requirements.txt

RUN /micromamba/bin/micromamba run -n backend pip install --no-deps "transformers[deepspeed]"
RUN /micromamba/bin/micromamba run -n backend pip install torch
RUN /micromamba/bin/micromamba run -n backend pip install transformers==4.38.2
RUN /micromamba/bin/micromamba run -n backend pip install peft==0.9.0
# RUN /micromamba/bin/micromamba run -n backend pip install flash-attn==2.5.6 --use-pep517
RUN /micromamba/bin/micromamba run -n backend pip install protobuf==4.25.3

RUN apt-get -y install libopenmpi-dev
RUN /micromamba/bin/micromamba run -n backend pip install mpi4py

# Use the gradio from source because latest version supports detecting root_path
# Reduces tons of work
# When this version is released, just use the new version
RUN /micromamba/bin/micromamba run -n backend pip install gradio==3.50.2

RUN /micromamba/bin/micromamba run -n backend pip3 install --upgrade setuptools
RUN /micromamba/bin/micromamba run -n backend pip3 install -vvv vllm==0.4.2 --use-pep517
RUN /micromamba/bin/micromamba run -n backend pip install lomo-optim==0.1.0
RUN /micromamba/bin/micromamba run -n backend pip install trl==0.7.11
RUN /micromamba/bin/micromamba run -n backend pip install transformers==4.38.2
RUN /micromamba/bin/micromamba run -n backend pip install bcrypt==4.0.1
WORKDIR /backend

# Copy the files
COPY . /backend

# Install the backend
WORKDIR /backend
RUN /micromamba/bin/micromamba run -n backend pip install -e .

RUN mkdir /logs
CMD /micromamba/bin/micromamba run -n backend uvicorn backend.main:app --host 0.0.0.0 --workers 4