export default interface FinetuneEntry {
	id: number;
	name: string;
	description: string;
	model_id: string
	dataset_id: string;
	devices: string;
	eval_indexes: string;
	output_dir: string;
	adapter_name: string;
	batch_size: number;
	micro_batch_size: number;
	num_epochs: number;
	learning_rate: number;
	cutoff_len: number;
	val_set_size: number;
	use_gradient_checkpointing: boolean;
	eval_step: number;
	save_step: number;
	logging_step: number;
	lora_r: number;
	lora_alpha: number;
	lora_dropout: number;
	num_virtual_tokens: number;
	train_on_inputs: boolean;
	group_by_length: boolean;
	bits_and_bytes: boolean;
	load_8bit: boolean;
	load_4bit: boolean;
	llm_int8_threshold: number;
	llm_int8_enable_fp32_cpu_offload: boolean;
	llm_int8_has_fp16_weight: boolean;
	bnb_4bit_compute_dtype: string;
	bnb_4bit_quant_type: string;
	bnb_4bit_use_double_quant: boolean;
	// 0训练 1完成 -1出错
	state: number;
	start_time: string;
	end_time?: string;
	zero_optimization: boolean;
	zero_optimization_stage: number;
	zero_offload: boolean;
}
